# 🐼 Introducción a Pandas en Python

Pandas es una de las librerías más populares de Python para **análisis y manipulación de datos**.  
Está construida sobre NumPy y proporciona estructuras de datos flexibles y eficientes, principalmente: Pandas Series y Pandas DataFrame

# Pandas Series

In [1]:
import pandas as pd

In [2]:
paises = pd.Series(['Argentina', 'Peru', 'Chile', 'Paraguay', 'Uruguay'])
paises

0    Argentina
1         Peru
2        Chile
3     Paraguay
4      Uruguay
dtype: object

In [3]:
type(paises)

pandas.core.series.Series

In [4]:
paises = pd.Series(['Perú','Chile','Colombia','Ecuador'],index=[1,3,5,7])
paises

1        Perú
3       Chile
5    Colombia
7     Ecuador
dtype: object

## CREAMOS PANDAS SERIES DESDE UN DICCIONARIO

In [5]:
dict = {
    1:'Perú',
    2:'Chile',
    3:'Colombia',
    4:'Ecuador'
}
pd.Series(dict)

1        Perú
2       Chile
3    Colombia
4     Ecuador
dtype: object

# Pandas DATAFRAME

In [6]:
dict = {
    'pais':['Perú','Chile','Colombia','Ecuador'],
    'pbi':[183,170,160,150],
    'habitantes':[33,22,22,50]
}
df_paises = pd.DataFrame(dict,index=[1,7,10,30])
df_paises

        pais  pbi  habitantes
1       Perú  183          33
7      Chile  170          22
10  Colombia  160          22
30   Ecuador  150          50

In [7]:
df_paises.columns

Index(['pais', 'pbi', 'habitantes'], dtype='object')

In [8]:
df_paises.index

Index([1, 7, 10, 30], dtype='int64')